### ISSUE TITLE
Switch to having serge generate javascript language files directly

### ISSUE THREAD

**Issue by devpow112** [Brightspace/d2l-outcomes-user-progress#99]
Looks like the option to have serge directly output *.js files was added at some point. This means we can eliminate the need to build our languages from `json` to `js` and just let serge do it directly. See https://github.com/BrightspaceUI/core/blob/master/core.serge.json

**Comment by rgoessl** [comment]
Done now?

**Comment by devpow112** [comment]
Fixed by #108
